/**
 * Pet registry - all available pet appearances
 * Each pet uses a sprite sheet with Canvas animation
 *
 * Animation layout (8 columns x N rows):
 *   Row 0: idle (first 3 frames, 1.8s loop)
 *   Other rows: random actions (auto-detected)
 */

export const PET_LIST = [
  { id: 'rem-xl', name: '雷姆', sprite: '/pets/rem-xl.webp', thumb: '/pets/thumbs/rem-xl.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'boba', name: 'Boba', sprite: '/pets/boba.webp', thumb: '/pets/thumbs/boba.webp', format: 'webp', cols: 8, rows: 11 },
  { id: 'boxcat', name: 'Boxcat', sprite: '/pets/boxcat.webp', thumb: '/pets/thumbs/boxcat.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'bubu', name: 'bubu', sprite: '/pets/bubu.webp', thumb: '/pets/thumbs/bubu.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'cache-capy', name: 'Cache Capy', sprite: '/pets/cache-capy.webp', thumb: '/pets/thumbs/cache-capy.webp', format: 'webp', cols: 8, rows: 11 },
  { id: 'mambo', name: 'Mambo', sprite: '/pets/mambo.webp', thumb: '/pets/thumbs/mambo.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'naruto', name: 'Naruto', sprite: '/pets/naruto.webp', thumb: '/pets/thumbs/naruto.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'pochita', name: 'Pochita', sprite: '/pets/pochita.webp', thumb: '/pets/thumbs/pochita.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'thorny-daily-v1', name: 'Thorny Daily v1', sprite: '/pets/thorny-daily-v1.webp', thumb: '/pets/thumbs/thorny-daily-v1.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'cloudy', name: 'Cloudy', sprite: '/pets/cloudy.webp', thumb: '/pets/thumbs/cloudy.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'yier', name: '一二', sprite: '/pets/yier.webp', thumb: '/pets/thumbs/yier.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'bunbun', name: 'Bunbun', sprite: '/pets/bunbun.webp', thumb: '/pets/thumbs/bunbun.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'hoops', name: 'Hoops', sprite: '/pets/hoops.webp', thumb: '/pets/thumbs/hoops.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'feibi', name: 'feibi', sprite: '/pets/feibi.webp', thumb: '/pets/thumbs/feibi.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'gugugaga', name: '咕咕嘎嘎', sprite: '/pets/gugugaga.webp', thumb: '/pets/thumbs/gugugaga.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'kitmar', name: 'Marin-chan', sprite: '/pets/kitmar.webp', thumb: '/pets/thumbs/kitmar.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'piney', name: 'Piney', sprite: '/pets/piney.webp', thumb: '/pets/thumbs/piney.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'pudding', name: 'Pudding', sprite: '/pets/pudding.webp', thumb: '/pets/thumbs/pudding.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'taolulu', name: 'TaoLuLu', sprite: '/pets/taolulu.webp', thumb: '/pets/thumbs/taolulu.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'zmjjkk', name: 'zmjjkk', sprite: '/pets/zmjjkk.webp', thumb: '/pets/thumbs/zmjjkk.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'ryo-yamada-bass', name: 'Ryo Yamada Bass', sprite: '/pets/ryo-yamada-bass.webp', thumb: '/pets/thumbs/ryo-yamada-bass.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'bochi-guitar', name: 'Bochi Guitar', sprite: '/pets/bochi-guitar.webp', thumb: '/pets/thumbs/bochi-guitar.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'giant-panda', name: 'Giant Panda', sprite: '/pets/giant-panda.webp', thumb: '/pets/thumbs/giant-panda.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'loopy', name: 'loopy', sprite: '/pets/loopy.webp', thumb: '/pets/thumbs/loopy.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'tenniskitty', name: 'TennisKitty', sprite: '/pets/tenniskitty.webp', thumb: '/pets/thumbs/tenniskitty.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'strawwy', name: 'strawwy', sprite: '/pets/strawwy.webp', thumb: '/pets/thumbs/strawwy.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'ribbon-soft', name: 'Ribbon Soft', sprite: '/pets/ribbon-soft.webp', thumb: '/pets/thumbs/ribbon-soft.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'capybaralulu', name: 'CapybaraLuLu', sprite: '/pets/capybaralulu.webp', thumb: '/pets/thumbs/capybaralulu.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'capy', name: 'Capy', sprite: '/pets/capy.webp', thumb: '/pets/thumbs/capy.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'orzeszek', name: 'Nutty', sprite: '/pets/orzeszek.webp', thumb: '/pets/thumbs/orzeszek.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'run-dimo', name: 'Dimo', sprite: '/pets/run-dimo.webp', thumb: '/pets/thumbs/run-dimo.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'blingbara', name: 'Blingbara', sprite: '/pets/blingbara.webp', thumb: '/pets/thumbs/blingbara.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'xiao-qie-peng', name: '小企鹅', sprite: '/pets/xiao-qie-peng.webp', thumb: '/pets/thumbs/xiao-qie-peng.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'codex-panda', name: 'codex-panda', sprite: '/pets/codex-panda.webp', thumb: '/pets/thumbs/codex-panda.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'zongzi', name: 'Zongzi', sprite: '/pets/zongzi.webp', thumb: '/pets/thumbs/zongzi.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'triple-t', name: 'Triple T', sprite: '/pets/triple-t.webp', thumb: '/pets/thumbs/triple-t.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'goose-default', name: 'goose', sprite: '/pets/goose-default.png', thumb: '/pets/thumbs/goose-default.webp', format: 'png', cols: 8, rows: 9 },
  { id: 'capvolt', name: 'Pikachu‌', sprite: '/pets/capvolt.webp', thumb: '/pets/thumbs/capvolt.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'kabi', name: '卡比兽', sprite: '/pets/kabi.webp', thumb: '/pets/thumbs/kabi.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'doubao', name: '豆包', sprite: '/pets/doubao.webp', thumb: '/pets/thumbs/doubao.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'ema', name: 'Ema', sprite: '/pets/ema.webp', thumb: '/pets/thumbs/ema.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'jiyi', name: '吉伊', sprite: '/pets/jiyi.webp', thumb: '/pets/thumbs/jiyi.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'kibshi', name: 'KIBSHI', sprite: '/pets/kibshi.webp', thumb: '/pets/thumbs/kibshi.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'panda-default', name: 'panda', sprite: '/pets/panda-default.png', thumb: '/pets/thumbs/panda-default.webp', format: 'png', cols: 8, rows: 9 },
  { id: 'mochi-bear', name: 'Mochi Bear', sprite: '/pets/mochi-bear.webp', thumb: '/pets/thumbs/mochi-bear.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'pumpkin', name: 'pumpkin', sprite: '/pets/pumpkin.webp', thumb: '/pets/thumbs/pumpkin.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'xiaobai', name: '小白', sprite: '/pets/xiaobai.webp', thumb: '/pets/thumbs/xiaobai.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'yuzu', name: 'yuzu', sprite: '/pets/yuzu.webp', thumb: '/pets/thumbs/yuzu.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'yuiju', name: 'yuiju', sprite: '/pets/yuiju.webp', thumb: '/pets/thumbs/yuiju.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'calico', name: 'Calico', sprite: '/pets/calico.webp', thumb: '/pets/thumbs/calico.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'cc-cat', name: 'CC猫', sprite: '/pets/cc-cat.webp', thumb: '/pets/thumbs/cc-cat.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'charles', name: '샤를', sprite: '/pets/charles.webp', thumb: '/pets/thumbs/charles.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'kaki', name: 'Kaki', sprite: '/pets/kaki.webp', thumb: '/pets/thumbs/kaki.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'mox', name: 'Mox', sprite: '/pets/mox.webp', thumb: '/pets/thumbs/mox.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'doraemon', name: 'Doraemon', sprite: '/pets/doraemon.webp', thumb: '/pets/thumbs/doraemon.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'nyanko-v2', name: 'Nyanko', sprite: '/pets/nyanko-v2.webp', thumb: '/pets/thumbs/nyanko-v2.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'silvertabby', name: 'SilverTabby', sprite: '/pets/silvertabby.webp', thumb: '/pets/thumbs/silvertabby.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'sunny', name: 'Sunny', sprite: '/pets/sunny.webp', thumb: '/pets/thumbs/sunny.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'wabi', name: 'Wabi', sprite: '/pets/wabi.webp', thumb: '/pets/thumbs/wabi.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'bolt', name: 'Bolt', sprite: '/pets/bolt.webp', thumb: '/pets/thumbs/bolt.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'claw-crawler', name: 'kuro-chan', sprite: '/pets/claw-crawler.webp', thumb: '/pets/thumbs/claw-crawler.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'diana', name: 'Diana', sprite: '/pets/diana.webp', thumb: '/pets/thumbs/diana.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'amagi', name: '天城', sprite: '/pets/amagi.webp', thumb: '/pets/thumbs/amagi.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'clawd', name: 'Clawd', sprite: '/pets/clawd.webp', thumb: '/pets/thumbs/clawd.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'dragon-default', name: 'dragon', sprite: '/pets/dragon-default.png', thumb: '/pets/thumbs/dragon-default.webp', format: 'png', cols: 8, rows: 9 },
  { id: 'eve', name: 'EVE', sprite: '/pets/eve.webp', thumb: '/pets/thumbs/eve.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'qinyiv3', name: 'qinyiv3', sprite: '/pets/qinyiv3.png', thumb: '/pets/thumbs/qinyiv3.webp', format: 'png', cols: 8, rows: 9 },
  { id: 'lando', name: 'Lando', sprite: '/pets/lando.webp', thumb: '/pets/thumbs/lando.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'little-mao-puppy', name: 'Little Mao Puppy', sprite: '/pets/little-mao-puppy.webp', thumb: '/pets/thumbs/little-mao-puppy.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'koda', name: 'Koda', sprite: '/pets/koda.webp', thumb: '/pets/thumbs/koda.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'tianyu-dragon', name: 'Tianyu Dragon', sprite: '/pets/tianyu-dragon.png', thumb: '/pets/thumbs/tianyu-dragon.webp', format: 'png', cols: 8, rows: 9 },
  { id: 'bluebolt-hatch', name: 'Bluebolt', sprite: '/pets/bluebolt-hatch.webp', thumb: '/pets/thumbs/bluebolt-hatch.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'douos-douos', name: 'DouOS', sprite: '/pets/douos-douos.webp', thumb: '/pets/thumbs/douos-douos.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'jinbao', name: 'Jinbao', sprite: '/pets/jinbao.webp', thumb: '/pets/thumbs/jinbao.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'dongfang-xinniang', name: '东方新娘', sprite: '/pets/dongfang-xinniang.webp', thumb: '/pets/thumbs/dongfang-xinniang.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'anon', name: 'Anon(千早爱音)', sprite: '/pets/anon.webp', thumb: '/pets/thumbs/anon.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'mofu', name: 'Yui', sprite: '/pets/mofu.png', thumb: '/pets/thumbs/mofu.webp', format: 'png', cols: 8, rows: 9 },
  { id: 'stormy', name: 'Stormy', sprite: '/pets/stormy.webp', thumb: '/pets/thumbs/stormy.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'succy', name: 'Succy', sprite: '/pets/succy.webp', thumb: '/pets/thumbs/succy.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'sakura', name: 'Sakura', sprite: '/pets/sakura.webp', thumb: '/pets/thumbs/sakura.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'tomorin', name: 'tomorin', sprite: '/pets/tomorin.webp', thumb: '/pets/thumbs/tomorin.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'da-zhuang', name: '大壮', sprite: '/pets/da-zhuang.webp', thumb: '/pets/thumbs/da-zhuang.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'daimao', name: 'Daimao', sprite: '/pets/daimao.webp', thumb: '/pets/thumbs/daimao.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'harry-poptart', name: 'Harry Poptart', sprite: '/pets/harry-poptart.webp', thumb: '/pets/thumbs/harry-poptart.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'anya', name: '阿尼亚', sprite: '/pets/anya.webp', thumb: '/pets/thumbs/anya.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'frieren', name: 'Frieren', sprite: '/pets/frieren.webp', thumb: '/pets/thumbs/frieren.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'kyojuro-rengoku', name: '炼狱杏寿郎', sprite: '/pets/kyojuro-rengoku.webp', thumb: '/pets/thumbs/kyojuro-rengoku.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'nezuko', name: 'Nezuko', sprite: '/pets/nezuko.webp', thumb: '/pets/thumbs/nezuko.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'luffy', name: 'Luffy', sprite: '/pets/luffy.webp', thumb: '/pets/thumbs/luffy.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'hedgehog', name: 'Hedgehog', sprite: '/pets/hedgehog.webp', thumb: '/pets/thumbs/hedgehog.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'kaori', name: 'Kaori', sprite: '/pets/kaori.webp', thumb: '/pets/thumbs/kaori.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'rx-78-2-gundam', name: 'RX-78-2 Gundam', sprite: '/pets/rx-78-2-gundam.webp', thumb: '/pets/thumbs/rx-78-2-gundam.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'nemesis', name: 'nemesis', sprite: '/pets/nemesis.webp', thumb: '/pets/thumbs/nemesis.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'baoer', name: 'Baoer', sprite: '/pets/baoer.webp', thumb: '/pets/thumbs/baoer.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'boolet', name: 'Boolet', sprite: '/pets/boolet.webp', thumb: '/pets/thumbs/boolet.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'monica', name: 'Monica', sprite: '/pets/monica.webp', thumb: '/pets/thumbs/monica.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'carole', name: 'Carole', sprite: '/pets/carole.webp', thumb: '/pets/thumbs/carole.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'java', name: 'Java', sprite: '/pets/java.webp', thumb: '/pets/thumbs/java.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'nightleaf', name: 'Xiao Hei', sprite: '/pets/nightleaf.webp', thumb: '/pets/thumbs/nightleaf.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'didi', name: '弟弟', sprite: '/pets/didi.webp', thumb: '/pets/thumbs/didi.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'soyo', name: 'Soyo', sprite: '/pets/soyo.webp', thumb: '/pets/thumbs/soyo.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'jiangjiang', name: 'jiangjiang', sprite: '/pets/jiangjiang.webp', thumb: '/pets/thumbs/jiangjiang.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'hana-v2', name: 'Hana v2', sprite: '/pets/hana-v2.webp', thumb: '/pets/thumbs/hana-v2.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'penguin-chick', name: 'Emperor Penguin Chick', sprite: '/pets/penguin-chick.webp', thumb: '/pets/thumbs/penguin-chick.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'elaina', name: 'Elaina', sprite: '/pets/elaina.webp', thumb: '/pets/thumbs/elaina.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'daodun', name: 'DaoDun', sprite: '/pets/daodun.webp', thumb: '/pets/thumbs/daodun.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'whaledou', name: 'whaledou', sprite: '/pets/whaledou.webp', thumb: '/pets/thumbs/whaledou.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'bombardiro', name: 'Bombardiro', sprite: '/pets/bombardiro.webp', thumb: '/pets/thumbs/bombardiro.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'flaskling', name: 'Flaskling', sprite: '/pets/flaskling.webp', thumb: '/pets/thumbs/flaskling.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'columbinya', name: 'Columbinya', sprite: '/pets/columbinya.webp', thumb: '/pets/thumbs/columbinya.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'hu-tao-pet', name: '小胡桃', sprite: '/pets/hu-tao-pet.webp', thumb: '/pets/thumbs/hu-tao-pet.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'ayaka', name: 'Ayaka - 神里凌华', sprite: '/pets/ayaka.webp', thumb: '/pets/thumbs/ayaka.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'xiaoyuan', name: '小缘', sprite: '/pets/xiaoyuan.webp', thumb: '/pets/thumbs/xiaoyuan.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'tian-long', name: 'Tian Long', sprite: '/pets/tian-long.webp', thumb: '/pets/thumbs/tian-long.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'nobu', name: 'Nobu', sprite: '/pets/nobu.webp', thumb: '/pets/thumbs/nobu.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'kun', name: '小只因', sprite: '/pets/kun.webp', thumb: '/pets/thumbs/kun.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'obito', name: 'Obito', sprite: '/pets/obito.webp', thumb: '/pets/thumbs/obito.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'tanjiro-kamado-balanced', name: 'Tanjiro', sprite: '/pets/tanjiro-kamado-balanced.webp', thumb: '/pets/thumbs/tanjiro-kamado-balanced.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'naifrog-2-0', name: '奶蛙2.0', sprite: '/pets/naifrog-2-0.webp', thumb: '/pets/thumbs/naifrog-2-0.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'vivimi-strict', name: '维维美', sprite: '/pets/vivimi-strict.webp', thumb: '/pets/thumbs/vivimi-strict.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'hachiware', name: 'Hachiware', sprite: '/pets/hachiware.webp', thumb: '/pets/thumbs/hachiware.webp', format: 'webp', cols: 8, rows: 9 },
  // XCW2 pets
  { id: 'bitboy', name: 'BitBoy', sprite: '/pets/bitboy.webp', thumb: '/pets/thumbs/bitboy.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'lian', name: 'Lian', sprite: '/pets/lian.webp', thumb: '/pets/thumbs/lian.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'jiahao', name: 'Jiahao', sprite: '/pets/jiahao.webp', thumb: '/pets/thumbs/jiahao.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'pilot-duo', name: 'Pilot Duo', sprite: '/pets/pilot-duo.webp', thumb: '/pets/thumbs/pilot-duo.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'zhunimo', name: '祝尼魔', sprite: '/pets/zhunimo.webp', thumb: '/pets/thumbs/zhunimo.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'pingu', name: 'Pingu', sprite: '/pets/pingu.webp', thumb: '/pets/thumbs/pingu.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'bananacat', name: 'BananaCat', sprite: '/pets/bananacat.webp', thumb: '/pets/thumbs/bananacat.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'ggbond', name: '猪猪侠', sprite: '/pets/ggbond.webp', thumb: '/pets/thumbs/ggbond.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'iu-chibi', name: 'IU Chibi', sprite: '/pets/iu-chibi.webp', thumb: '/pets/thumbs/iu-chibi.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'one-punch-pet', name: 'One-Punch Pet', sprite: '/pets/one-punch-pet.webp', thumb: '/pets/thumbs/one-punch-pet.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'spongebob-star', name: 'SpongeBob', sprite: '/pets/spongebob-star.webp', thumb: '/pets/thumbs/spongebob-star.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'jiaran', name: '嘉然', sprite: '/pets/jiaran.webp', thumb: '/pets/thumbs/jiaran.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'ghost', name: 'Ghost', sprite: '/pets/ghost.webp', thumb: '/pets/thumbs/ghost.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'basketball-codex', name: '打篮球的坤哥', sprite: '/pets/basketball-codex.webp', thumb: '/pets/thumbs/basketball-codex.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'kitty1', name: 'Kitty 1', sprite: '/pets/kitty1.webp', thumb: '/pets/thumbs/kitty1.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'leaflings', name: 'Leaflings', sprite: '/pets/leaflings.webp', thumb: '/pets/thumbs/leaflings.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'hutao', name: '胡桃', sprite: '/pets/hutao.webp', thumb: '/pets/thumbs/hutao.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'firefly', name: 'Firefly', sprite: '/pets/firefly.webp', thumb: '/pets/thumbs/firefly.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'asuka', name: 'Asuka', sprite: '/pets/asuka.webp', thumb: '/pets/thumbs/asuka.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'little-knight', name: 'Little Knight', sprite: '/pets/little-knight.webp', thumb: '/pets/thumbs/little-knight.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'mahiro', name: 'Mahiro', sprite: '/pets/mahiro.webp', thumb: '/pets/thumbs/mahiro.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'wukong', name: 'Wukong', sprite: '/pets/wukong.webp', thumb: '/pets/thumbs/wukong.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'paimo', name: 'Paimo', sprite: '/pets/paimo.webp', thumb: '/pets/thumbs/paimo.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'patrick-star', name: 'Patrick Star', sprite: '/pets/patrick-star.webp', thumb: '/pets/thumbs/patrick-star.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'nailong', name: '奶龙', sprite: '/pets/nailong.webp', thumb: '/pets/thumbs/nailong.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'steve', name: 'Steve', sprite: '/pets/steve.webp', thumb: '/pets/thumbs/steve.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'bananboo', name: 'Bananboo', sprite: '/pets/bananboo.webp', thumb: '/pets/thumbs/bananboo.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'inu', name: 'Inu', sprite: '/pets/inu.webp', thumb: '/pets/thumbs/inu.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'rikka', name: '小鸟游六花', sprite: '/pets/rikka.webp', thumb: '/pets/thumbs/rikka.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'conan', name: 'Conan', sprite: '/pets/conan.webp', thumb: '/pets/thumbs/conan.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'xiaoyu-jade', name: '小玉', sprite: '/pets/xiaoyu-jade.webp', thumb: '/pets/thumbs/xiaoyu-jade.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'takagi', name: '高木', sprite: '/pets/takagi.webp', thumb: '/pets/thumbs/takagi.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'theveller', name: 'TheVeller', sprite: '/pets/theveller.webp', thumb: '/pets/thumbs/theveller.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'hana', name: 'Hana', sprite: '/pets/hana.webp', thumb: '/pets/thumbs/hana.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'asuka-q', name: '明日香Q', sprite: '/pets/asuka-q.webp', thumb: '/pets/thumbs/asuka-q.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'qqpet-codex', name: 'QQpet-codex', sprite: '/pets/qqpet-codex.png', thumb: '/pets/thumbs/qqpet-codex.webp', format: 'png', cols: 8, rows: 9 },
  { id: 'a-tom', name: 'A Tom', sprite: '/pets/a-tom.webp', thumb: '/pets/thumbs/a-tom.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'capoo', name: 'capoo', sprite: '/pets/capoo.webp', thumb: '/pets/thumbs/capoo.webp', format: 'webp', cols: 8, rows: 9 },
  { id: 'doro', name: 'Doro', sprite: '/pets/doro.webp', thumb: '/pets/thumbs/doro.webp', format: 'webp', cols: 8, rows: 9 }
]

export const DEFAULT_PET_ID = 'codex-panda'
